package com.mido.elearning.enums;

public enum Country {
        AFGHANISTAN("Afghanistan", "+93", "AF"),
        ALAND_ISLANDS("Aland Islands", "+358", "AX"),
        ALBANIA("Albania", "+355", "AL"),
        ALGERIA("Algeria", "+213", "DZ"),
        AMERICAN_SAMOA("AmericanSamoa", "+1684", "AS"),
        ANDORRA("Andorra", "+376", "AD"),
        ANGOLA("Angola", "+244", "AO"),
        ANGUILLA("Anguilla", "+1264", "AI"),
        ANTARCTICA("Antarctica", "+672", "AQ"),
        ANTIGUA_AND_BARBUDA("Antigua and Barbuda", "+1268", "AG"),
        ARGENTINA("Argentina", "+54", "AR"),
        ARMENIA("Armenia", "+374", "AM"),
        ARUBA("Aruba", "+297", "AW"),
        AUSTRALIA("Australia", "+61", "AU"),
        AUSTRIA("Austria", "+43", "AT"),
        AZERBAIJAN("Azerbaijan", "+994", "AZ"),
        BAHAMAS("Bahamas", "+1242", "BS"),
        BAHRAIN("Bahrain", "+973", "BH"),
        BANGLADESH("Bangladesh", "+880", "BD"),
        BARBADOS("Barbados", "+1246", "BB"),
        BELARUS("Belarus", "+375", "BY"),
        BELGIUM("Belgium", "+32", "BE"),
        BELIZE("Belize", "+501", "BZ"),
        BENIN("Benin", "+229", "BJ"),
        BERMUDA("Bermuda", "+1441", "BM"),
        BHUTAN("Bhutan", "+975", "BT"),
        BOLIVIA("Bolivia, Plurinational State of", "+591", "BO"),
        BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina", "+387", "BA"),
        BOTSWANA("Botswana", "+267", "BW"),
        BRAZIL("Brazil", "+55", "BR"),
        BRITISH_INDIAN_OCEAN_TERRITORY("British Indian Ocean Territory", "+246", "IO"),
        BRUNEI_DARUSSALAM("Brunei Darussalam", "+673", "BN"),
        BULGARIA("Bulgaria", "+359", "BG"),
        BURKINA_FASO("Burkina Faso", "+226", "BF"),
        BURUNDI("Burundi", "+257", "BI"),
        CAMBODIA("Cambodia", "+855", "KH"),
        CAMEROON("Cameroon", "+237", "CM"),
        CANADA("Canada", "+1", "CA"),
        CAPE_VERDE("Cape Verde", "+238", "CV"),
        CAYMAN_ISLANDS("Cayman Islands", "+ 345", "KY"),
        CENTRAL_AFRICAN_REPUBLIC("Central African Republic", "+236", "CF"),
        CHAD("Chad", "+235", "TD"),
        CHILE("Chile", "+56", "CL"),
        CHINA("China", "+86", "CN"),
        CHRISTMAS_ISLAND("Christmas Island", "+61", "CX"),
        COCOS_KEELING_ISLANDS("Cocos (Keeling) Islands", "+61", "CC"),
        COLOMBIA("Colombia", "+57", "CO"),
        COMOROS("Comoros", "+269", "KM"),
        CONGO("Congo", "+242", "CG"),
        CONGO_DEMOCRATIC_REPUBLIC("Congo, The Democratic Republic of the Congo", "+243", "CD"),
        COOK_ISLANDS("Cook Islands", "+682", "CK"),
        COSTA_RICA("Costa Rica", "+506", "CR"),
        COTE_DIVOIRE("Cote d'Ivoire", "+225", "CI"),
        CROATIA("Croatia", "+385", "HR"),
        CUBA("Cuba", "+53", "CU"),
        CYPRUS("Cyprus", "+357", "CY"),
        CZECH_REPUBLIC("Czech Republic", "+420", "CZ"),
        DENMARK("Denmark", "+45", "DK"),
        DJIBOUTI("Djibouti", "+253", "DJ"),
        DOMINICA("Dominica", "+1767", "DM"),
        DOMINICAN_REPUBLIC("Dominican Republic", "+1849", "DO"),
        ECUADOR("Ecuador", "+593", "EC"),
        EGYPT("Egypt", "+20", "EG"),
        EL_SALVADOR("El Salvador", "+503", "SV"),
        EQUATORIAL_GUINEA("Equatorial Guinea", "+240", "GQ"),
        ERITREA("Eritrea", "+291", "ER"),
        ESTONIA("Estonia", "+372", "EE"),
        ETHIOPIA("Ethiopia", "+251", "ET"),
        FALKLAND_ISLANDS("Falkland Islands (Malvinas)", "+500", "FK"),
        FAROE_ISLANDS("Faroe Islands", "+298", "FO"),
        FIJI("Fiji", "+679", "FJ"),
        FINLAND("Finland", "+358", "FI"),
        FRANCE("France", "+33", "FR"),
        FRENCH_GUIANA("French Guiana", "+594", "GF"),
        FRENCH_POLYNESIA("French Polynesia", "+689", "PF"),
        GABON("Gabon", "+241", "GA"),
        GAMBIA("Gambia", "+220", "GM"),
        GEORGIA("Georgia", "+995", "GE"),
        GERMANY("Germany", "+49", "DE"),
        GHANA("Ghana", "+233", "GH"),
        GIBRALTAR("Gibraltar", "+350", "GI"),
        GREECE("Greece", "+30", "GR"),
        GREENLAND("Greenland", "+299", "GL"),
        GRENADA("Grenada", "+1473", "GD"),
        GUADELOUPE("Guadeloupe", "+590", "GP"),
        GUAM("Guam", "+1671", "GU"),
        GUATEMALA("Guatemala", "+502", "GT"),
        GUERNSEY("Guernsey", "+44", "GG"),
        GUINEA("Guinea", "+224", "GN"),
        GUINEA_BISSAU("Guinea-Bissau", "+245", "GW"),
        GUYANA("Guyana", "+595", "GY"),
        HAITI("Haiti", "+509", "HT"),
        HOLY_SEE("Holy See (Vatican City State)", "+379", "VA"),
        HONDURAS("Honduras", "+504", "HN"),
        HONG_KONG("Hong Kong", "+852", "HK"),
        HUNGARY("Hungary", "+36", "HU"),
        ICELAND("Iceland", "+354", "IS"),
        INDIA("India", "+91", "IN"),
        INDONESIA("Indonesia", "+62", "ID"),
        IRAN("Iran, Islamic Republic of", "+98", "IR"),
        IRAQ("Iraq", "+964", "IQ"),
        IRELAND("Ireland", "+353", "IE"),
        ISLE_OF_MAN("Isle of Man", "+44", "IM"),
        ISRAEL("Israel", "+972", "IL"),
        ITALY("Italy", "+39", "IT"),
        JAMAICA("Jamaica", "+1876", "JM"),
        JAPAN("Japan", "+81", "JP"),
        JERSEY("Jersey", "+44", "JE"),
        JORDAN("Jordan", "+962", "JO"),
        KAZAKHSTAN("Kazakhstan", "+7", "KZ"),
        KENYA("Kenya", "+254", "KE"),
        KIRIBATI("Kiribati", "+686", "KI"),
        KOREA("Korea, Democratic People's Republic of", "+850", "KP"),
        KOREA_REPUBLIC_OF("Korea, Republic of", "+82", "KR"),
        KUWAIT("Kuwait", "+965", "KW"),
        KYRGYZSTAN("Kyrgyzstan", "+996", "KG"),
        LAO_PEOPLES_DEMOCRATIC_REPUBLIC("Lao People's Democratic Republic", "+856", "LA"),
        LATVIA("Latvia", "+371", "LV"),
        LEBANON("Lebanon", "+961", "LB"),
        LESOTHO("Lesotho", "+266", "LS"),
        LIBERIA("Liberia", "+231", "LR"),
        LIBYAN_ARAB_JAMAHIRIYA("Libyan Arab Jamahiriya", "+218", "LY"),
        LIECHTENSTEIN("Liechtenstein", "+423", "LI"),
        LITHUANIA("Lithuania", "+370", "LT"),
        LUXEMBOURG("Luxembourg", "+352", "LU"),
        MACAO("Macao", "+853", "MO"),
        MACEDONIA("Macedonia, The Former Yugoslav Republic of", "+389", "MK"),
        MADAGASCAR("Madagascar", "+261", "MG"),
        MALAWI("Malawi", "+265", "MW"),
        MALAYSIA("Malaysia", "+60", "MY"),
        MALDIVES("Maldives", "+960", "MV"),
        MALI("Mali", "+223", "ML"),
        MALTA("Malta", "+356", "MT"),
        MARSHALL_ISLANDS("Marshall Islands", "+692", "MH"),
        MARTINIQUE("Martinique", "+596", "MQ"),
        MAURITANIA("Mauritania", "+222", "MR"),
        MAURITIUS("Mauritius", "+230", "MU"),
        MAYOTTE("Mayotte", "+262", "YT"),
        MEXICO("Mexico", "+52", "MX"),
        MICRONESIA("Micronesia, Federated States of", "+691", "FM"),
        MOLDOVA("Moldova, Republic of", "+373", "MD"),
        MONACO("Monaco", "+377", "MC"),
        MONGOLIA("Mongolia", "+976", "MN"),
        MONTENEGRO("Montenegro", "+382", "ME"),
        MONTSERRAT("Montserrat", "+1664", "MS"),
        MOROCCO("Morocco", "+212", "MA"),
        MOZAMBIQUE("Mozambique", "+258", "MZ"),
        MYANMAR("Myanmar", "+95", "MM"),
        NAMIBIA("Namibia", "+264", "NA"),
        NAURU("Nauru", "+674", "NR"),
        NEPAL("Nepal", "+977", "NP"),
        NETHERLANDS("Netherlands", "+31", "NL"),
        NETHERLANDS_ANTILLES("Netherlands Antilles", "+599", "AN"),
        NEW_CALEDONIA("New Caledonia", "+687", "NC"),
        NEW_ZEALAND("New Zealand", "+64", "NZ"),
        NICARAGUA("Nicaragua", "+505", "NI"),
        NIGER("Niger", "+227", "NE"),
        NIGERIA("Nigeria", "+234", "NG"),
        NIUE("Niue", "+683", "NU"),
        NORFOLK_ISLAND("Norfolk Island", "+672", "NF"),
        NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands", "+1670", "MP"),
        NORWAY("Norway", "+47", "NO"),
        OMAN("Oman", "+968", "OM"),
        PAKISTAN("Pakistan", "+92", "PK"),
        PALAU("Palau", "+680", "PW"),
        PALESTINIAN_TERRITORY("Palestinian Territory, Occupied", "+970", "PS"),
        PANAMA("Panama", "+507", "PA"),
        PAPUA_NEW_GUINEA("Papua New Guinea", "+675", "PG"),
        PARAGUAY("Paraguay", "+595", "PY"),
        PERU("Peru", "+51", "PE"),
        PHILIPPINES("Philippines", "+63", "PH"),
        PITCAIRN("Pitcairn", "+872", "PN"),
        POLAND("Poland", "+48", "PL"),
        PORTUGAL("Portugal", "+351", "PT"),
        PUERTO_RICO("Puerto Rico", "+1939", "PR"),
        QATAR("Qatar", "+974", "QA"),
        REUNION("Reunion", "+262", "RE"),
        ROMANIA("Romania", "+40", "RO"),
        RUSSIAN_FEDERATION("Russian Federation", "+7", "RU"),
        RWANDA("Rwanda", "+250", "RW"),
        SAINT_BARTHELEMY("Saint Barthelemy", "+590", "BL"),
        SAINT_HELENA("Saint Helena", "+290", "SH"),
        SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis", "+1869", "KN"),
        SAINT_LUCIA("Saint Lucia", "+1758", "LC"),
        SAINT_MARTIN("Saint Martin", "+590", "MF"),
        SAINT_PIERRE_AND_MIQUELON("Saint Pierre and Miquelon", "+508", "PM"),
        SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines", "+1784", "VC"),
        SAMOA("Samoa", "+685", "WS"),
        SAN_MARINO("San Marino", "+378", "SM"),
        SAO_TOME_AND_PRINCIPE("Sao Tome and Principe", "+239", "ST"),
        SAUDI_ARABIA("Saudi Arabia", "+966", "SA"),
        SENEGAL("Senegal", "+221", "SN"),
        SERBIA("Serbia", "+381", "RS"),
        SEYCHELLES("Seychelles", "+248", "SC"),
        SIERRA_LEONE("Sierra Leone", "+232", "SL"),
        SINGAPORE("Singapore", "+65", "SG"),
        SLOVAKIA("Slovakia", "+421", "SK"),
        SLOVENIA("Slovenia", "+386", "SI"),
        SOLOMON_ISLANDS("Solomon Islands", "+677", "SB"),
        SOMALIA("Somalia", "+252", "SO"),
        SOUTH_AFRICA("South Africa", "+27", "ZA"),
        SOUTH_SUDAN("South Sudan", "+211", "SS"),
        SPAIN("Spain", "+34", "ES"),
        SRI_LANKA("Sri Lanka", "+94", "LK"),
        SUDAN("Sudan", "+249", "SD"),
        SURINAME("Suriname", "+597", "SR"),
        SVALBARD_AND_JAN_MAYEN("Svalbard and Jan Mayen", "+47", "SJ"),
        SWAZILAND("Swaziland", "+268", "SZ"),
        SWEDEN("Sweden", "+46", "SE"),
        SWITZERLAND("Switzerland", "+41", "CH"),
        SYRIAN_ARAB_REPUBLIC("Syrian Arab Republic", "+963", "SY"),
        TAIWAN("Taiwan, Province of China", "+886", "TW"),
        TAJIKISTAN("Tajikistan", "+992", "TJ"),
        TANZANIA("Tanzania, United Republic of", "+255", "TZ"),
        THAILAND("Thailand", "+66", "TH"),
        TIMOR_LESTE("Timor-Leste", "+670", "TL"),
        TOGO("Togo", "+228", "TG"),
        TOKELAU("Tokelau", "+690", "TK"),
        TONGA("Tonga", "+676", "TO"),
        TRINIDAD_AND_TOBAGO("Trinidad and Tobago", "+1868", "TT"),
        TUNISIA("Tunisia", "+216", "TN"),
        TURKEY("Turkey", "+90", "TR"),
        TURKMENISTAN("Turkmenistan", "+993", "TM"),
        TURKS_AND_CAICOS_ISLANDS("Turks and Caicos Islands", "+1649", "TC"),
        TUVALU("Tuvalu", "+688", "TV"),
        UGANDA("Uganda", "+256", "UG"),
        UKRAINE("Ukraine", "+380", "UA"),
        UNITED_ARAB_EMIRATES("United Arab Emirates", "+971", "AE"),
        UNITED_KINGDOM("United Kingdom", "+44", "GB"),
        UNITED_STATES("United States", "+1", "US"),
        URUGUAY("Uruguay", "+598", "UY"),
        UZBEKISTAN("Uzbekistan", "+998", "UZ"),
        VANUATU("Vanuatu", "+678", "VU"),
        VENEZUELA("Venezuela", "+58", "VE"),
        VIETNAM("Viet Nam", "+84", "VN"),
        VIRGIN_ISLANDS_BRITISH("Virgin Islands, British", "+1284", "VG"),
        VIRGIN_ISLANDS_US("Virgin Islands, U.S.", "+1340", "VI"),
        WALLIS_AND_FUTUNA("Wallis and Futuna", "+681", "WF"),
        WESTERN_SAHARA("Western Sahara", "+212", "EH"),
        YEMEN("Yemen", "+967", "YE"),
        ZAMBIA("Zambia", "+260", "ZM"),
        ZIMBABWE("Zimbabwe", "+263", "ZW");

        private final String name;
        private final String dialCode;
        private final String code;

    Country(String name, String dialCode, String code) {
            this.name = name;
            this.dialCode = dialCode;
            this.code = code;
        }

        public String getCode(String cName) {
            return Country.valueOf(cName).toString();

        }

    }